version: "2"

services:
  builder:
    container_name: "yocto-builder"
    hostname: "yocto-builder"
    image: "ci/yocto-builder"
    build:
      context: .
      args:
        ubuntu_version: "18.04"
        builder_username: "guest"
        builder_password: "guest"
        domain_name: "smileylab.o.uk"
        docker_version: "19.03.8"
        docker_group_id: "133" # `getent group docker | cut -d: -f3`
        toolchain: "gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu"
        extra_pkgs: "gawk wget git-core diffstat unzip texinfo gcc-multilib g++-multilib build-essential \
chrpath socat cpio python python3 python3-pip python3-pexpect python-dev \
xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev xterm \
coreutils texi2html file docbook-utils \
python-pysqlite2 help2man desktop-file-utils \
libgl1-mesa-dev libglu1-mesa-dev mercurial autoconf automake \
groff lzop asciidoc u-boot-tools libreoffice-writer \
sshpass ssh-askpass zip kpartx repo qemu sudo curl vim"
        sshd_port: 22
    volumes:
      - "/mnt/yocto:/home/jenkins/workspace"
      - "/var/run/docker.sock:/var/run/docker.sock"
