version: "2"

services:
  builder:
    container_name: "yocto-builder"
    hostname: "yocto-builder"
    image: "docker-slave/yocto-builder"
    build:
      context: .
      args:
        builder_username: "guest"
        builder_password: "guest"
        toolchain: "gcc-5.1-2015.08-x86_64_arm-linux-gnueabihf gcc-linaro-6.4.1-2017.11-x86_64_aarch64-linux-gnu arm-2010.09-50-arm-none-linux-gnueabi-i686-pc-linux-gnu"
        extra_pkgs: "gawk wget git-core git-lfs diffstat unzip texinfo gcc-multilib g++-multilib build-essential \
chrpath socat cpio python python3 python3-pip python3-pexpect python-dev \
xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev xterm \
coreutils texi2html file docbook-utils \
python-pysqlite2 help2man desktop-file-utils \
libgl1-mesa-dev libglu1-mesa-dev mercurial autoconf automake \
groff lzop asciidoc u-boot-tools libreoffice-writer \
sshpass ssh-askpass zip kpartx repo qemu"
        sshd_port: 22
    volumes:
      - "/home/admin/workspace/src/yocto2.5/download:/home/jenkins/downloads"
      - "/home/admin/workspace/src/yocto2.5/sstat:/home/jenkins/sstate-cache"
      - "/home/admin/workspace/src/yocto2.5/ccache:/home/jenkins/ccache"
